//! Module containing the deserialized representation of the config generated via the NixOS modules
//! system config for nimi

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

use crate::process_manager::{Service, Settings};

/// Per-service ordering constraints
#[derive(Debug, Default, Serialize, Deserialize)]
pub struct ServiceOrdering {
    /// Services that must have started before this one is spawned
    #[serde(default)]
    pub after: Vec<String>,
    /// Services that must be ready before this one starts (requires readyCheck on target)
    #[serde(default, rename = "afterReady")]
    pub after_ready: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize)]
/// Representation of the nimi config generated by evaluating a nimi services module
///
/// Create this by using the nix package to run `nimi.mkNimiBin`
pub struct Config {
    /// Deserializable representation of services
    pub services: HashMap<String, Service>,

    /// Process manager settings
    pub settings: Settings,

    /// Service startup ordering constraints
    #[serde(default)]
    pub ordering: HashMap<String, ServiceOrdering>,
}
